#!/bin/bash

DIR=$(dirname $0)
VUNIT_ROOT=$DIR'/src/vunit.vim'
OUT_FILE=$DIR'output.txt'
RESULT_FILE=$DIR'result.txt'

files=$(find $1 -type f -follow -name '*test.vim' -printf "'%p',")
files=${files::-1}

runner=$2

run_tests() {
    touch ${OUT_FILE}
    touch ${RESULT_FILE}

    if [[ $1 == 'nvim' ]]; then
        nvim --headless -u ${VUNIT_ROOT} -c "call  Execute([${files}], '${OUT_FILE}', '${RESULT_FILE}')|q"
    else
        vim -u ${VUNIT_ROOT} -c "call  Execute([${files}], '${OUT_FILE}', '${RESULT_FILE}')|q"
    fi

    out=$(cat ${OUT_FILE})
    echo -e "${out}"
    rm ${OUT_FILE}
    result=$(cat ${RESULT_FILE})
    rm ${RESULT_FILE}

    if [[ $result =~ FAILED ]]; then
        return 1
    else
        return 0
    fi
}

if [[ $runner == '--nvim' ]]; then
    echo '=== Running tests with Neovim ==='
    run_tests nvim
    exit $?
fi

if [[ $runner == '--vim' ]]; then
    echo '=== Running tests with Vim ==='
    run_tests vim
    exit $?
fi

echo 'No running specified'
exit 1

